package company.ryzhkov.util

object Constants {
  val TooLongFields = "Длина поля не более 100 символов"
  val UsernameTooLong = "Имя пользователя слишком длинное"
  val UsernameIsEmpty = "Имя пользователя отсутствует"
  val PasswordTooLong = "Пароль слишком длинный"
  val PasswordTooShort = "Пароль слишком короткий (не меннее 5 символов)"
  val PasswordIsEmpty = "Пароль отсутствует"
  val EmailTooLong = "Email слишком длинный"
  val FillAllFields = "Заполните все поля"
  val PasswordsDoNotMatch = "Пароли не совпадают"
  val UserCreated = "Успешная регистрация"
  val UserNotFound = "Пользователь не найден"
  val UsernameAlreadyExists = "Имя пользователя существует"
  val EmailAlreadyExists = "Email уже существует"
  val AccessDenied = "Доступ запрещен"
  val InvalidUsernameOrPassword = "Неправильное имя пользователя или пароль"
  val FirstNameTooLong = "Имя не более 100 символов"
  val SecondNameTooLong = "Фамилия не более 100 символов"
  val PhoneNumberInvalid = "Некорректный телефон"
  val UserUpdated = "Пользователь изменен"
  val UserDeleted = "Пользователь удален"
  val Too_Long_Field = "Размер поля превышает 100 символов"
  val IncorrectUserName = "Некорректное имя пользователя"
  val IncorrectEmail = "Некорреткный email"
  val IncorrectPassword = "Некорректный пароль"
  val IncorrectFirstName = "Некорректное имя"
  val IncorrectSecondName = "Некорректная фамилия"
  val IncorrectPhoneNumber = "Некорректный номер телефона"
  val ObjectNotFound = "Объект не найден"
  val ReplyContentTooLong = "Размер сообщения превышает 1000 символов"
  val ReplyAdded = "Комментарий добавлен"
  val PasswordUpdated = "Пароль изменен"
  val RecallCreated = "Мы получили Ваш отзыв"
  val Text1500 = "Текст не более 1500 символов"
}
